-- Baseline: schema gerado pelo Hibernate (ddl-auto=update) ate a adocao do Flyway.
-- Extraido via pg_dump --schema-only do banco semac2026 em 2026-07-29.

-- =========================================================================
-- Tabelas
-- =========================================================================

CREATE TABLE public.caixa_fundunesp (
    id integer NOT NULL,
    data_atualizacao timestamp(6) without time zone NOT NULL,
    valor numeric(10,2) NOT NULL,
    atualizado_por integer
);

ALTER TABLE public.caixa_fundunesp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.caixa_fundunesp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.camisa_pedido (
    id integer NOT NULL,
    modelo character varying(255) NOT NULL,
    tamanho character varying(255) NOT NULL,
    pessoa_id integer NOT NULL,
    CONSTRAINT camisa_pedido_modelo_check CHECK (((modelo)::text = ANY ((ARRAY['NORMAL'::character varying, 'BABY_LOOK'::character varying])::text[]))),
    CONSTRAINT camisa_pedido_tamanho_check CHECK (((tamanho)::text = ANY ((ARRAY['PP'::character varying, 'P'::character varying, 'M'::character varying, 'G'::character varying, 'GG'::character varying])::text[])))
);

ALTER TABLE public.camisa_pedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.camisa_pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.compra (
    id integer NOT NULL,
    descricao character varying(255) NOT NULL,
    categoria character varying(50) NOT NULL,
    fornecedor_id integer NOT NULL,
    valor_unitario numeric(10,2) NOT NULL,
    quantidade integer NOT NULL,
    valor_total numeric(10,2) NOT NULL,
    data_compra timestamp without time zone NOT NULL
);

CREATE SEQUENCE public.compra_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.compra_id_seq OWNED BY public.compra.id;

CREATE TABLE public.conquista (
    id integer NOT NULL,
    imagem_url character varying(255),
    nome character varying(255) NOT NULL,
    pontos_base integer NOT NULL,
    raridade integer NOT NULL
);

ALTER TABLE public.conquista ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conquista_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.cota (
    id integer NOT NULL,
    nivel character varying(20) NOT NULL,
    valor numeric(10,2) NOT NULL
);

CREATE SEQUENCE public.cota_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.cota_id_seq OWNED BY public.cota.id;

CREATE TABLE public.doador (
    id integer NOT NULL,
    nome character varying(255) NOT NULL,
    valor numeric(10,2) NOT NULL,
    data timestamp without time zone NOT NULL
);

CREATE SEQUENCE public.doador_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.doador_id_seq OWNED BY public.doador.id;

CREATE TABLE public.evento (
    id integer NOT NULL,
    capacidade_maxima integer NOT NULL,
    data_hora_inicio timestamp(6) without time zone NOT NULL,
    descricao character varying(255),
    nome character varying(255) NOT NULL,
    tipo_evento_id integer NOT NULL,
    local character varying(255),
    data_hora_fim timestamp without time zone NOT NULL
);

ALTER TABLE public.evento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.evento_palestrante (
    evento_id integer NOT NULL,
    palestrante_id integer NOT NULL
);

CREATE TABLE public.evento_participante (
    status smallint NOT NULL,
    evento_id integer NOT NULL,
    participante_id integer NOT NULL,
    CONSTRAINT evento_participante_status_check CHECK (((status >= 0) AND (status <= 2)))
);

CREATE TABLE public.fornecedor (
    id integer NOT NULL,
    contato character varying(255),
    nome character varying(255) NOT NULL,
    observacao character varying(255)
);

ALTER TABLE public.fornecedor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fornecedor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.ganhadores_sorteio (
    sorteio_id integer NOT NULL,
    ganhou_em timestamp(6) without time zone NOT NULL,
    participante_id integer NOT NULL
);

CREATE TABLE public.palestrante (
    id integer NOT NULL,
    descricao character varying(255),
    nome character varying(255) NOT NULL
);

ALTER TABLE public.palestrante ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.palestrante_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.participante_conquista (
    obtida_em timestamp(6) without time zone NOT NULL,
    conquista_id integer NOT NULL,
    participante_id integer NOT NULL
);

CREATE TABLE public.patrocinador (
    id integer NOT NULL,
    descricao character varying(255),
    logo_url character varying(255),
    nome character varying(255) NOT NULL,
    adicao numeric(10,2),
    data_recebimento timestamp(6) without time zone,
    desconto numeric(10,2),
    observacao character varying(255),
    status_pagamento character varying(255) NOT NULL,
    valor_final numeric(10,2),
    cota_id integer NOT NULL,
    CONSTRAINT patrocinador_status_pagamento_check CHECK (((status_pagamento)::text = ANY ((ARRAY['A_RECEBER'::character varying, 'RECEBIDO'::character varying])::text[])))
);

ALTER TABLE public.patrocinador ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.patrocinador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.pessoa (
    id integer NOT NULL,
    ativo boolean NOT NULL,
    cpf character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    nome character varying(255) NOT NULL,
    ra character varying(255),
    role character varying(255),
    senha character varying(255) NOT NULL,
    uuid character varying(255) NOT NULL,
    tipo_inscricao_id integer,
    comprovante_pagamento character varying(255),
    CONSTRAINT pessoa_role_check CHECK (((role)::text = ANY ((ARRAY['PARTICIPANTE'::character varying, 'MEMBRO'::character varying, 'DIRETOR_SITE'::character varying, 'DIRETOR_CONTEUDO'::character varying, 'DIRETOR_PATROCINIO'::character varying, 'DIRETOR_APOIO'::character varying, 'PRESIDENTE'::character varying])::text[])))
);

ALTER TABLE public.pessoa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pessoa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.sorteio (
    id integer NOT NULL,
    realizado_em timestamp(6) without time zone NOT NULL,
    evento_id integer NOT NULL,
    organizador_id integer NOT NULL
);

ALTER TABLE public.sorteio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sorteio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.tipo_evento (
    id integer NOT NULL,
    nome character varying(255) NOT NULL,
    pontos integer NOT NULL
);

ALTER TABLE public.tipo_evento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipo_evento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.tipo_inscricao (
    id integer NOT NULL,
    nome character varying(255) NOT NULL,
    valor numeric(10,2) NOT NULL,
    ano integer NOT NULL,
    ativo boolean DEFAULT true NOT NULL
);

CREATE SEQUENCE public.tipo_inscricao_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.tipo_inscricao_id_seq OWNED BY public.tipo_inscricao.id;

-- =========================================================================
-- Defaults (sequences criadas manualmente, nao via IDENTITY)
-- =========================================================================

ALTER TABLE ONLY public.compra ALTER COLUMN id SET DEFAULT nextval('public.compra_id_seq'::regclass);
ALTER TABLE ONLY public.cota ALTER COLUMN id SET DEFAULT nextval('public.cota_id_seq'::regclass);
ALTER TABLE ONLY public.doador ALTER COLUMN id SET DEFAULT nextval('public.doador_id_seq'::regclass);
ALTER TABLE ONLY public.tipo_inscricao ALTER COLUMN id SET DEFAULT nextval('public.tipo_inscricao_id_seq'::regclass);

-- =========================================================================
-- Primary keys e constraints unique
-- =========================================================================

ALTER TABLE ONLY public.caixa_fundunesp ADD CONSTRAINT caixa_fundunesp_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.camisa_pedido ADD CONSTRAINT camisa_pedido_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.compra ADD CONSTRAINT compra_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.conquista ADD CONSTRAINT conquista_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.cota ADD CONSTRAINT cota_nivel_key UNIQUE (nivel);
ALTER TABLE ONLY public.cota ADD CONSTRAINT cota_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.doador ADD CONSTRAINT doador_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.evento_palestrante ADD CONSTRAINT evento_palestrante_pkey PRIMARY KEY (evento_id, palestrante_id);
ALTER TABLE ONLY public.evento_participante ADD CONSTRAINT evento_participante_pkey PRIMARY KEY (evento_id, participante_id);
ALTER TABLE ONLY public.evento ADD CONSTRAINT evento_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.fornecedor ADD CONSTRAINT fornecedor_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ganhadores_sorteio ADD CONSTRAINT ganhadores_sorteio_pkey PRIMARY KEY (sorteio_id);
ALTER TABLE ONLY public.palestrante ADD CONSTRAINT palestrante_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.participante_conquista ADD CONSTRAINT participante_conquista_pkey PRIMARY KEY (conquista_id, participante_id);
ALTER TABLE ONLY public.patrocinador ADD CONSTRAINT patrocinador_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.pessoa ADD CONSTRAINT pessoa_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.sorteio ADD CONSTRAINT sorteio_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tipo_evento ADD CONSTRAINT tipo_evento_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tipo_inscricao ADD CONSTRAINT tipo_inscricao_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.pessoa ADD CONSTRAINT uk33hpky9wy60hlom6fblimfvai UNIQUE (uuid);
ALTER TABLE ONLY public.pessoa ADD CONSTRAINT ukmc87q8fpvldpdyfo9o5633o5l UNIQUE (email);
ALTER TABLE ONLY public.pessoa ADD CONSTRAINT uknlwiu48rutiltbnjle59krljo UNIQUE (cpf);
ALTER TABLE ONLY public.tipo_inscricao ADD CONSTRAINT uq_tipo_inscricao_nome_ano UNIQUE (nome, ano);

-- =========================================================================
-- Foreign keys
-- =========================================================================

ALTER TABLE ONLY public.ganhadores_sorteio ADD CONSTRAINT fk17be8omuoku029ir2pf56jjme FOREIGN KEY (sorteio_id) REFERENCES public.sorteio(id);
ALTER TABLE ONLY public.participante_conquista ADD CONSTRAINT fk2ob1olmxef0wvpaibd765jo0i FOREIGN KEY (conquista_id) REFERENCES public.conquista(id);
ALTER TABLE ONLY public.ganhadores_sorteio ADD CONSTRAINT fk50jmpsf70cuwepuu2qimaym2l FOREIGN KEY (participante_id) REFERENCES public.pessoa(id);
ALTER TABLE ONLY public.evento ADD CONSTRAINT fk6w38aahpdken3763tw3m3sbou FOREIGN KEY (tipo_evento_id) REFERENCES public.tipo_evento(id);
ALTER TABLE ONLY public.sorteio ADD CONSTRAINT fk7fkvexkjwg7c64i2k6ikrw1ee FOREIGN KEY (evento_id) REFERENCES public.evento(id);
ALTER TABLE ONLY public.compra ADD CONSTRAINT fk_compra_fornecedor FOREIGN KEY (fornecedor_id) REFERENCES public.fornecedor(id);
ALTER TABLE ONLY public.patrocinador ADD CONSTRAINT fk_patrocinador_cota FOREIGN KEY (cota_id) REFERENCES public.cota(id);
ALTER TABLE ONLY public.pessoa ADD CONSTRAINT fk_pessoa_tipo_inscricao FOREIGN KEY (tipo_inscricao_id) REFERENCES public.tipo_inscricao(id);
ALTER TABLE ONLY public.participante_conquista ADD CONSTRAINT fka3e4vgkp1i85pu1y79tj367fv FOREIGN KEY (participante_id) REFERENCES public.pessoa(id);
ALTER TABLE ONLY public.evento_palestrante ADD CONSTRAINT fkarftes05dmxrh67xi818r428d FOREIGN KEY (palestrante_id) REFERENCES public.palestrante(id);
ALTER TABLE ONLY public.sorteio ADD CONSTRAINT fkf7nf1v4t0n6x95b8uocl00ghy FOREIGN KEY (organizador_id) REFERENCES public.pessoa(id);
ALTER TABLE ONLY public.evento_participante ADD CONSTRAINT fkic78i29tkyb9bisdvmy4hswuq FOREIGN KEY (participante_id) REFERENCES public.pessoa(id);
ALTER TABLE ONLY public.evento_participante ADD CONSTRAINT fkn7waivg5h9hmd8cbl1hfu29dw FOREIGN KEY (evento_id) REFERENCES public.evento(id);
ALTER TABLE ONLY public.evento_palestrante ADD CONSTRAINT fkp3opkwn31cum2u53yjshtkaho FOREIGN KEY (evento_id) REFERENCES public.evento(id);
ALTER TABLE ONLY public.camisa_pedido ADD CONSTRAINT fkpt3v79at1e2lxkmsq523rhrqe FOREIGN KEY (pessoa_id) REFERENCES public.pessoa(id);
ALTER TABLE ONLY public.caixa_fundunesp ADD CONSTRAINT fksbq36you5b0hme5sobwll136r FOREIGN KEY (atualizado_por) REFERENCES public.pessoa(id);
