-- Módulo de Cotação: itens sendo cotados (ainda não comprados), cada um
-- podendo ter várias linhas de fornecedor com preços diferentes.

CREATE TABLE public.cotacao (
    id integer NOT NULL,
    descricao character varying(255) NOT NULL,
    categoria character varying(50) NOT NULL,
    quantidade integer NOT NULL
);

ALTER TABLE public.cotacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cotacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.cotacao ADD CONSTRAINT cotacao_pkey PRIMARY KEY (id);

CREATE TABLE public.cotacao_fornecedor (
    id integer NOT NULL,
    cotacao_id integer NOT NULL,
    fornecedor_id integer NOT NULL,
    valor_unitario numeric(10,2) NOT NULL
);

ALTER TABLE public.cotacao_fornecedor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cotacao_fornecedor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.cotacao_fornecedor ADD CONSTRAINT cotacao_fornecedor_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.cotacao_fornecedor ADD CONSTRAINT uq_cotacao_fornecedor UNIQUE (cotacao_id, fornecedor_id);

ALTER TABLE ONLY public.cotacao_fornecedor ADD CONSTRAINT fk_cotacao_fornecedor_cotacao FOREIGN KEY (cotacao_id) REFERENCES public.cotacao(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.cotacao_fornecedor ADD CONSTRAINT fk_cotacao_fornecedor_fornecedor FOREIGN KEY (fornecedor_id) REFERENCES public.fornecedor(id);
