-- Conjuntos de cotação: agrupam itens já cotados (produto + fornecedor
-- escolhido + quantidade) para montar e comparar o custo de opções
-- (ex.: Coffee Break Opção A x Opção B). O preço vem da linha de
-- cotacao_fornecedor referenciada — não é duplicado aqui.

CREATE TABLE public.conjunto (
    id integer NOT NULL,
    nome character varying(255) NOT NULL
);

ALTER TABLE public.conjunto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conjunto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.conjunto ADD CONSTRAINT conjunto_pkey PRIMARY KEY (id);

CREATE TABLE public.conjunto_item (
    id integer NOT NULL,
    conjunto_id integer NOT NULL,
    cotacao_fornecedor_id integer NOT NULL,
    quantidade integer NOT NULL
);

ALTER TABLE public.conjunto_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conjunto_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.conjunto_item ADD CONSTRAINT conjunto_item_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.conjunto_item ADD CONSTRAINT uq_conjunto_item UNIQUE (conjunto_id, cotacao_fornecedor_id);

ALTER TABLE ONLY public.conjunto_item ADD CONSTRAINT fk_conjunto_item_conjunto FOREIGN KEY (conjunto_id) REFERENCES public.conjunto(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.conjunto_item ADD CONSTRAINT fk_conjunto_item_cotacao_fornecedor FOREIGN KEY (cotacao_fornecedor_id) REFERENCES public.cotacao_fornecedor(id) ON DELETE CASCADE;
