-- Substitui o modelo de conjunto (lista única de itens) pelo de variações
-- comparáveis: um conjunto (ex.: "Coffee") passa a ter várias variações
-- (ex.: "Coffee Cheio" x "Coffee Reduzido"), cada uma com suas próprias
-- quantidades por item cotado. A feature é nova e sem uso em produção
-- ainda, então o conteúdo de conjunto_item pode ser descartado.

DROP TABLE public.conjunto_item;

CREATE TABLE public.variacao (
    id integer NOT NULL,
    conjunto_id integer NOT NULL,
    nome character varying(255) NOT NULL
);

ALTER TABLE public.variacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.variacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.variacao ADD CONSTRAINT variacao_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.variacao ADD CONSTRAINT uq_variacao_nome UNIQUE (conjunto_id, nome);
ALTER TABLE ONLY public.variacao ADD CONSTRAINT fk_variacao_conjunto FOREIGN KEY (conjunto_id) REFERENCES public.conjunto(id) ON DELETE CASCADE;

CREATE TABLE public.variacao_item (
    id integer NOT NULL,
    variacao_id integer NOT NULL,
    cotacao_fornecedor_id integer NOT NULL,
    quantidade integer NOT NULL
);

ALTER TABLE public.variacao_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.variacao_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.variacao_item ADD CONSTRAINT variacao_item_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.variacao_item ADD CONSTRAINT uq_variacao_item UNIQUE (variacao_id, cotacao_fornecedor_id);

ALTER TABLE ONLY public.variacao_item ADD CONSTRAINT fk_variacao_item_variacao FOREIGN KEY (variacao_id) REFERENCES public.variacao(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.variacao_item ADD CONSTRAINT fk_variacao_item_cotacao_fornecedor FOREIGN KEY (cotacao_fornecedor_id) REFERENCES public.cotacao_fornecedor(id) ON DELETE CASCADE;
