-- Níveis de participante: nome + xp mínimo pra alcançá-lo. Pessoa
-- ganha xp inicial e nível na confirmação da inscrição (ver
-- PessoaService.atribuirRole); o acúmulo contínuo de xp por
-- conquistas/presenças é uma entrega futura.

CREATE TABLE public.nivel (
    id integer NOT NULL,
    nome character varying(255) NOT NULL,
    xp_minimo integer NOT NULL
);

ALTER TABLE public.nivel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nivel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.nivel ADD CONSTRAINT nivel_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.nivel ADD CONSTRAINT uq_nivel_nome UNIQUE (nome);
ALTER TABLE ONLY public.nivel ADD CONSTRAINT uq_nivel_xp_minimo UNIQUE (xp_minimo);

ALTER TABLE public.pessoa ADD COLUMN nivel_id integer;
ALTER TABLE public.pessoa ADD COLUMN xp integer;
ALTER TABLE ONLY public.pessoa ADD CONSTRAINT fk_pessoa_nivel FOREIGN KEY (nivel_id) REFERENCES public.nivel(id);
